OPS-2407 Ensure error messages go to stderr

diff --git a/templates/kops-create.sh.j2 b/templates/kops-create.sh.j2
--- a/templates/kops-create.sh.j2
+++ b/templates/kops-create.sh.j2
@@ -34,7 +34,7 @@ if [ "${RUN}" -eq "1" ]; then
 	fi
 {% endfor %}
 	if [ "${FOUND}" -ne "1" ]; then
-		echo "Error, ${AWS_ACCOUNT} is not allowed."
+		>&2 echo "Error, ${AWS_ACCOUNT} is not allowed."
 		exit 1
 	fi
 fi
